#ifndef ESP_ARDUINO_VERSION_H
#define ESP_ARDUINO_VERSION_H

#define ESP_ARDUINO_VERSION_MAJOR 3
#define ESP_ARDUINO_VERSION_MINOR 1
#define ESP_ARDUINO_VERSION_PATCH 2

#define ESP_ARDUINO_VERSION_STRING "3.1.2"

#endif